### ISSUE TITLE
EDM issue

### ISSUE THREAD

**Issue by anhnt** [anhnt/paspaley#3]
When I receive the EDM in my iPhone it is displaying strange "preview" body text in both my Hotmail and Gmail accounts, see attached. Could you please fix?

Also, I noticed in the EDM that you need to change the footer unsubscribe link to read "To unsubscribe please click here".
![image1](https://cloud.githubusercontent.com/assets/735555/9683905/4de3acfe-533e-11e5-8c53-a1f6418eb711.PNG)
![image2](https://cloud.githubusercontent.com/assets/735555/9683906/4de81e56-533e-11e5-9cdc-af6de883d846.PNG)

**Comment by anhnt** [comment]
@lettiem I've fixed it. Can you please test it again? Thanks

**Comment by lettiem** [comment]
@anhnt have tested this on Yahoo Mail and Hotmail. It is fine in Yahoo Mail. But in Hotmail it is still appearing with that strange preview message. How do we fix this?

**Comment by anhnt** [comment]
@lettiem does it look like the second image?

**Comment by lettiem** [comment]
@anhnt Yes it looks like the second image. I haven't been able to test Gmail as it keeps saying I'm already registered.

**Comment by anhnt** [comment]
@lettiem please go to here http://admin.paspaley.olhub.com/groups/2015-Registrations/members/ to delete your records

**Comment by lettiem** [comment]
@anhnt I'm trying to login to Kademi and it won't let me get in. Are you able to check if my account lettiem@chemistri.com.au has admin access?

**Comment by lettiem** [comment]
@anhnt I am still getting that strange preview message (second screenshot) in my hotmail.It works fine in Gmail, Yahoo and my Chemistri email.

**Comment by anhnt** [comment]
@lettiem you are able to login now. Please try again. I will figure out this hotmail issue

**Comment by lettiem** [comment]
@anhnt can't login to admin of kademi, keeps saying my login is incorrect. Can you please set my username and passord to this:
U: lettiem@chemistri.com.au
P: letstar321

**Comment by anhnt** [comment]
@lettiem Please login using above details

**Comment by anhnt** [comment]
@lettiem I've fixed this issue on hotmail account. Can you please test it again? See the first email on the attached
![hotmail](https://cloud.githubusercontent.com/assets/735555/9708396/3cafc22a-5545-11e5-8d20-682bb899a115.jpg)
